services:
  - type: web
    name: bgl-vobi-relatorio
    runtime: python
    plan: free
    region: ohio
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /health
    envVars:
      - key: REPORT_USER
        value: bgl
      - key: REPORT_PASSWORD
        sync: false
